/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Dao.ModulodConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class Atualizar_Dados_Anuncio extends javax.swing.JInternalFrame {

    /**
     * Creates new form Atualizar_Dados_Anuncio
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String nomeUsuario;
    int idUsuario, idImovel;

    public Atualizar_Dados_Anuncio(String nome) {
        initComponents();
        conexao = ModulodConexao.conector();
        nomeUsuario = nome;
    }

    public void setarCamposImovel() {
        String sql = "select * from tbimovel";
        String sql2 = "select * from tbanuncio";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {   
                txtBairro.setText(rs.getString("bairro"));
                pst.setString(2, cbxTipoImovel.getSelectedItem().toString());
                txtNrCasa.setText(rs.getString("nr_casa"));
                txtQuarteirao.setText(rs.getString("quarteirao"));
                if (cbxTipoImovel.getSelectedItem().toString().equalsIgnoreCase("Casa")) {
                    txtDimensao.setText(rs.getString("dimensao"));
                    pst.setInt(6, 0);
                } else if (cbxTipoImovel.getSelectedItem().toString().equalsIgnoreCase("Apartamento")) {
                    pst.setString(5, "null");
                    txtAndar.setText(rs.getString("andar"));
                }
                txtDescrisao.setText(rs.getString("descricao"));
                txtPreco.setText(rs.getString("preco"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(0, 153, 153));
    }

    private void resetColor(JPanel panel) {
        panel.setBackground(java.awt.Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnelComponentes = new javax.swing.JPanel();
        cbxCriteriodPesquisar1 = new javax.swing.JComboBox();
        txtPesquisar1 = new javax.swing.JTextField();
        lblPesquisar1 = new javax.swing.JLabel();
        jSeparatorPesquisar1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblePesquisarAnuncio = new javax.swing.JTable();
        cbxTipoImovel = new javax.swing.JComboBox();
        lblTipoImovel = new javax.swing.JLabel();
        lblDataAnuncio = new javax.swing.JLabel();
        jDateData = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        lblLargura = new javax.swing.JLabel();
        lblAndar = new javax.swing.JLabel();
        lblNrCasa = new javax.swing.JLabel();
        txtNrCasa = new javax.swing.JTextField();
        pnelAndar = new javax.swing.JPanel();
        txtAndar = new javax.swing.JTextField();
        pnelLargura = new javax.swing.JPanel();
        txtDimensao = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jSeparatorBairro = new javax.swing.JSeparator();
        lblQuarteirao = new javax.swing.JLabel();
        txtQuarteirao = new javax.swing.JTextField();
        jSeparatorQuarteirao = new javax.swing.JSeparator();
        txtPreco = new javax.swing.JTextField();
        jSeparatorQuarteirao1 = new javax.swing.JSeparator();
        lblPreco = new javax.swing.JLabel();
        txtDescrisao = new javax.swing.JTextField();
        jSeparatorDescrisao = new javax.swing.JSeparator();
        lblDescrisao = new javax.swing.JLabel();
        cbxTipoAnuncio = new javax.swing.JComboBox();
        lblTipoAnuncio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        pnelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        pnelComponentes.setBackground(new java.awt.Color(255, 255, 255));

        cbxCriteriodPesquisar1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        cbxCriteriodPesquisar1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo de anúncio", "Tipo de imóvel" }));

        txtPesquisar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPesquisar1.setText("Pesquisar");
        txtPesquisar1.setBorder(null);
        txtPesquisar1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisar1FocusGained(evt);
            }
        });

        lblPesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/search_50px_1.png"))); // NOI18N

        tblePesquisarAnuncio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo de anúncio", "Data de publicação", "Tipo de imóvel", "Publicado por"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblePesquisarAnuncio);

        cbxTipoImovel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbxTipoImovel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Casa", "Apartamento" }));
        cbxTipoImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoImovelActionPerformed(evt);
            }
        });

        lblTipoImovel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTipoImovel.setText("* Tipo de imóvel");

        lblDataAnuncio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDataAnuncio.setText("* Data do anúncio");

        jDateData.setBackground(new java.awt.Color(255, 255, 255));
        jDateData.setDateFormatString("yyyy-MM-dd");

        jLabel2.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel2.setText("(ano-MÊS-dia)");

        lblLargura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblLargura.setText("* Dimensão");

        lblAndar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAndar.setText("* Andar");

        lblNrCasa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNrCasa.setText("*Nr. casa");

        pnelAndar.setBackground(java.awt.Color.red);

        javax.swing.GroupLayout pnelAndarLayout = new javax.swing.GroupLayout(pnelAndar);
        pnelAndar.setLayout(pnelAndarLayout);
        pnelAndarLayout.setHorizontalGroup(
            pnelAndarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAndar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnelAndarLayout.setVerticalGroup(
            pnelAndarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAndar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        pnelLargura.setBackground(java.awt.Color.red);

        javax.swing.GroupLayout pnelLarguraLayout = new javax.swing.GroupLayout(pnelLargura);
        pnelLargura.setLayout(pnelLarguraLayout);
        pnelLarguraLayout.setHorizontalGroup(
            pnelLarguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelLarguraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtDimensao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnelLarguraLayout.setVerticalGroup(
            pnelLarguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDimensao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        lblBairro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblBairro.setText("* Bairro");

        txtBairro.setBorder(null);

        lblQuarteirao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblQuarteirao.setText("* Quarteirão");

        txtQuarteirao.setBorder(null);

        txtPreco.setBorder(null);

        lblPreco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPreco.setText("* Preço");

        txtDescrisao.setBorder(null);

        lblDescrisao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDescrisao.setText("* Descrisão");

        cbxTipoAnuncio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Venda", "Aluguel" }));

        lblTipoAnuncio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTipoAnuncio.setText("Tipo de anúncio");

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Atualizar");

        javax.swing.GroupLayout pnelComponentesLayout = new javax.swing.GroupLayout(pnelComponentes);
        pnelComponentes.setLayout(pnelComponentesLayout);
        pnelComponentesLayout.setHorizontalGroup(
            pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelComponentesLayout.createSequentialGroup()
                .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelComponentesLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(cbxCriteriodPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPesquisar1)
                            .addComponent(jSeparatorPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPesquisar1))
                    .addGroup(pnelComponentesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTipoAnuncio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxTipoAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelComponentesLayout.createSequentialGroup()
                .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnelComponentesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(pnelComponentesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblDescrisao)
                        .addGap(18, 18, 18)
                        .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparatorDescrisao)
                            .addComponent(txtDescrisao))
                        .addGap(101, 101, 101)
                        .addComponent(lblPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparatorQuarteirao1)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnelComponentesLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblBairro)
                        .addGap(18, 18, 18)
                        .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparatorBairro)
                            .addComponent(txtBairro))
                        .addGap(67, 67, 67)
                        .addComponent(lblQuarteirao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparatorQuarteirao)
                            .addComponent(txtQuarteirao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnelComponentesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTipoImovel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxTipoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelComponentesLayout.createSequentialGroup()
                                .addComponent(lblDataAnuncio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateData, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelComponentesLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(44, 44, 44))))
                    .addGroup(pnelComponentesLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblLargura)
                        .addGap(18, 18, 18)
                        .addComponent(pnelLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236)
                        .addComponent(lblAndar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnelAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(lblNrCasa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNrCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
            .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnelComponentesLayout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );
        pnelComponentesLayout.setVerticalGroup(
            pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelComponentesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelComponentesLayout.createSequentialGroup()
                        .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCriteriodPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparatorPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPesquisar1))
                .addGap(233, 233, 233)
                .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnelComponentesLayout.createSequentialGroup()
                        .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoImovel)
                            .addComponent(cbxTipoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataAnuncio))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)))
                .addGap(34, 34, 34)
                .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNrCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNrCasa))
                    .addComponent(pnelLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnelComponentesLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblLargura))
                    .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnelComponentesLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(lblAndar)
                            .addGap(8, 8, 8))
                        .addComponent(pnelAndar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnelComponentesLayout.createSequentialGroup()
                        .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBairro)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparatorBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnelComponentesLayout.createSequentialGroup()
                        .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuarteirao)
                            .addComponent(txtQuarteirao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparatorQuarteirao, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelComponentesLayout.createSequentialGroup()
                        .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescrisao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescrisao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparatorDescrisao, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnelComponentesLayout.createSequentialGroup()
                        .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPreco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparatorQuarteirao1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoAnuncio)
                    .addComponent(cbxTipoAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(pnelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnelComponentesLayout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(476, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(pnelComponentes);

        javax.swing.GroupLayout pnelPrincipalLayout = new javax.swing.GroupLayout(pnelPrincipal);
        pnelPrincipal.setLayout(pnelPrincipalLayout);
        pnelPrincipalLayout.setHorizontalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );
        pnelPrincipalLayout.setVerticalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisar1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisar1FocusGained
        // TODO add your handling code here:
        txtPesquisar1.setText("");
    }//GEN-LAST:event_txtPesquisar1FocusGained

    private void cbxTipoImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoImovelActionPerformed
        // TODO add your handling code here:
        if (cbxTipoImovel.getSelectedItem().toString().equals("Casa")) {
            setColor(pnelLargura);
            resetColor(pnelAndar);
        } else if (cbxTipoImovel.getSelectedItem().toString().equals("Apartamento")) {
            resetColor(pnelLargura);
            setColor(pnelAndar);
        }
    }//GEN-LAST:event_cbxTipoImovelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxCriteriodPesquisar1;
    private javax.swing.JComboBox cbxTipoAnuncio;
    private javax.swing.JComboBox cbxTipoImovel;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateData;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparatorBairro;
    private javax.swing.JSeparator jSeparatorDescrisao;
    private javax.swing.JSeparator jSeparatorPesquisar1;
    private javax.swing.JSeparator jSeparatorQuarteirao;
    private javax.swing.JSeparator jSeparatorQuarteirao1;
    private javax.swing.JLabel lblAndar;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblDataAnuncio;
    private javax.swing.JLabel lblDescrisao;
    private javax.swing.JLabel lblLargura;
    private javax.swing.JLabel lblNrCasa;
    private javax.swing.JLabel lblPesquisar1;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQuarteirao;
    private javax.swing.JLabel lblTipoAnuncio;
    private javax.swing.JLabel lblTipoImovel;
    private javax.swing.JPanel pnelAndar;
    private javax.swing.JPanel pnelComponentes;
    private javax.swing.JPanel pnelLargura;
    private javax.swing.JPanel pnelPrincipal;
    private javax.swing.JTable tblePesquisarAnuncio;
    private javax.swing.JTextField txtAndar;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtDescrisao;
    private javax.swing.JTextField txtDimensao;
    private javax.swing.JTextField txtNrCasa;
    private javax.swing.JTextField txtPesquisar1;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuarteirao;
    // End of variables declaration//GEN-END:variables
}
