/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Dao.ModulodConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Painel_Usuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Painel_Usuario
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Painel_Principal principal;
    String nomeUsuario;
    Sistema_Venda_Arendamento s;

    public Painel_Usuario(String nome) {
        initComponents();
        conexao = ModulodConexao.conector();
        nomeUsuario = nome;
        consultar();
    }
    
    public void setNomeUsuario(String nome) {
        nomeUsuario = nome;
    }

    private void consultar() {
        String sql = "select nome,nomeUsuario,senha,telefone from tbUsuario where nomeUsuario=" + "'" +nomeUsuario+"'";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                txtNome.setText(rs.getString("nome"));
                txtNomeUsuario.setText(rs.getString("nomeUsuario"));
                txtSenha.setText(rs.getString("senha"));
                txtTelefone.setText(rs.getString("telefone"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnelPrincipal = new javax.swing.JPanel();
        pnelMenus = new javax.swing.JPanel();
        btnPesquisar = new javax.swing.JPanel();
        lblIconPesquisar = new javax.swing.JLabel();
        lblPesquisar = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JPanel();
        lblIconAtualizar = new javax.swing.JLabel();
        lblAtualizar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        lblIconEliminar = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        pnelPaineis = new javax.swing.JPanel();
        pnelDadosPessoais = new javax.swing.JPanel();
        lblNomeCompleto = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jSeparatorNome = new javax.swing.JSeparator();
        lblUsuario = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        jSeparatorUsuario = new javax.swing.JSeparator();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        jSeparatorSenha = new javax.swing.JSeparator();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jSeparatorTelefone = new javax.swing.JSeparator();
        pnelCaregarPaineis = new javax.swing.JPanel();
        jDesktopPaneCaregarPaineis = new javax.swing.JDesktopPane();
        lblVoltar = new javax.swing.JLabel();

        pnelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        pnelMenus.setBackground(new java.awt.Color(255, 255, 255));

        btnPesquisar.setBackground(new java.awt.Color(0, 153, 153));
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
        });

        lblIconPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/view_50px_3.png"))); // NOI18N

        lblPesquisar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lblPesquisar.setText("Pesquisar usuários");

        javax.swing.GroupLayout btnPesquisarLayout = new javax.swing.GroupLayout(btnPesquisar);
        btnPesquisar.setLayout(btnPesquisarLayout);
        btnPesquisarLayout.setHorizontalGroup(
            btnPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPesquisar)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        btnPesquisarLayout.setVerticalGroup(
            btnPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPesquisarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(btnPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPesquisar)
                    .addComponent(lblIconPesquisar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnAtualizar.setBackground(new java.awt.Color(0, 153, 153));
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtualizarMouseClicked(evt);
            }
        });

        lblIconAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/update_file_50px_1.png"))); // NOI18N

        lblAtualizar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        lblAtualizar.setText("Atualizar dados");

        javax.swing.GroupLayout btnAtualizarLayout = new javax.swing.GroupLayout(btnAtualizar);
        btnAtualizar.setLayout(btnAtualizarLayout);
        btnAtualizarLayout.setHorizontalGroup(
            btnAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAtualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAtualizar)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        btnAtualizarLayout.setVerticalGroup(
            btnAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAtualizarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(btnAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAtualizar)
                    .addComponent(lblIconAtualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEliminar.setBackground(new java.awt.Color(0, 153, 153));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        lblIconEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/delete_file_50px_1.png"))); // NOI18N

        lblEliminar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setText("Apagar conta");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEliminar)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconEliminar)
                    .addComponent(lblEliminar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout pnelMenusLayout = new javax.swing.GroupLayout(pnelMenus);
        pnelMenus.setLayout(pnelMenusLayout);
        pnelMenusLayout.setHorizontalGroup(
            pnelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelMenusLayout.createSequentialGroup()
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnelMenusLayout.setVerticalGroup(
            pnelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnelPaineis.setLayout(new java.awt.CardLayout());

        pnelDadosPessoais.setBackground(new java.awt.Color(255, 255, 255));

        lblNomeCompleto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNomeCompleto.setText("* Nome completo");

        txtNome.setEditable(false);
        txtNome.setToolTipText("Campo nao editavel");
        txtNome.setBorder(null);
        txtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUsuario.setText("* Nome do usuário");

        txtNomeUsuario.setEditable(false);
        txtNomeUsuario.setToolTipText("Campo nao editavel");
        txtNomeUsuario.setBorder(null);
        txtNomeUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSenha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSenha.setText("* Senha");

        txtSenha.setEditable(false);
        txtSenha.setToolTipText("Campo nao editavel");
        txtSenha.setBorder(null);
        txtSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblTelefone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTelefone.setText("* Telefone");

        txtTelefone.setEditable(false);
        txtTelefone.setToolTipText("Campo nao editavel");
        txtTelefone.setBorder(null);
        txtTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnelDadosPessoaisLayout = new javax.swing.GroupLayout(pnelDadosPessoais);
        pnelDadosPessoais.setLayout(pnelDadosPessoaisLayout);
        pnelDadosPessoaisLayout.setHorizontalGroup(
            pnelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTelefone)
                    .addComponent(lblUsuario)
                    .addComponent(lblNomeCompleto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparatorTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                    .addGroup(pnelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparatorNome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnelDadosPessoaisLayout.createSequentialGroup()
                            .addGroup(pnelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparatorUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNomeUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)
                            .addComponent(lblSenha)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pnelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparatorSenha)
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnelDadosPessoaisLayout.setVerticalGroup(
            pnelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelDadosPessoaisLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCompleto)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(pnelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparatorSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(pnelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pnelPaineis.add(pnelDadosPessoais, "card2");

        javax.swing.GroupLayout jDesktopPaneCaregarPaineisLayout = new javax.swing.GroupLayout(jDesktopPaneCaregarPaineis);
        jDesktopPaneCaregarPaineis.setLayout(jDesktopPaneCaregarPaineisLayout);
        jDesktopPaneCaregarPaineisLayout.setHorizontalGroup(
            jDesktopPaneCaregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );
        jDesktopPaneCaregarPaineisLayout.setVerticalGroup(
            jDesktopPaneCaregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnelCaregarPaineisLayout = new javax.swing.GroupLayout(pnelCaregarPaineis);
        pnelCaregarPaineis.setLayout(pnelCaregarPaineisLayout);
        pnelCaregarPaineisLayout.setHorizontalGroup(
            pnelCaregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneCaregarPaineis)
        );
        pnelCaregarPaineisLayout.setVerticalGroup(
            pnelCaregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneCaregarPaineis)
        );

        pnelPaineis.add(pnelCaregarPaineis, "card3");

        lblVoltar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Back.png"))); // NOI18N
        lblVoltar.setText("Voltar");
        lblVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnelPrincipalLayout = new javax.swing.GroupLayout(pnelPrincipal);
        pnelPrincipal.setLayout(pnelPrincipalLayout);
        pnelPrincipalLayout.setHorizontalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelMenus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnelPaineis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnelPrincipalLayout.setVerticalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelPrincipalLayout.createSequentialGroup()
                .addComponent(pnelMenus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(lblVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnelPaineis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        // TODO add your handling code here:
        pnelDadosPessoais.hide();
        pnelCaregarPaineis.show();
        jDesktopPaneCaregarPaineis.show();
        Pesquisar_Usuario pesquisar_usuario = new Pesquisar_Usuario();
        pesquisar_usuario.setVisible(true);
        if (jDesktopPaneCaregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCaregarPaineis.add(pesquisar_usuario);
        } else {
            jDesktopPaneCaregarPaineis.remove(0);
            jDesktopPaneCaregarPaineis.add(pesquisar_usuario);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizarMouseClicked
        // TODO add your handling code here:
        pnelDadosPessoais.hide();
        pnelCaregarPaineis.show();
        jDesktopPaneCaregarPaineis.show();
        Atualizar_Dados_Usuario atualizar_dados = new Atualizar_Dados_Usuario(nomeUsuario);
        atualizar_dados.setVisible(true);
        if (jDesktopPaneCaregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCaregarPaineis.add(atualizar_dados);
        } else {
            jDesktopPaneCaregarPaineis.remove(0);
            jDesktopPaneCaregarPaineis.add(atualizar_dados);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_btnAtualizarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "bolachas");
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void lblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseClicked
        // TODO add your handling code here: 
        pnelCaregarPaineis.hide();
        pnelDadosPessoais.show();
    }//GEN-LAST:event_lblVoltarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAtualizar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnPesquisar;
    private javax.swing.JDesktopPane jDesktopPaneCaregarPaineis;
    private javax.swing.JSeparator jSeparatorNome;
    private javax.swing.JSeparator jSeparatorSenha;
    private javax.swing.JSeparator jSeparatorTelefone;
    private javax.swing.JSeparator jSeparatorUsuario;
    private javax.swing.JLabel lblAtualizar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblIconAtualizar;
    private javax.swing.JLabel lblIconEliminar;
    private javax.swing.JLabel lblIconPesquisar;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVoltar;
    private javax.swing.JPanel pnelCaregarPaineis;
    private javax.swing.JPanel pnelDadosPessoais;
    private javax.swing.JPanel pnelMenus;
    private javax.swing.JPanel pnelPaineis;
    private javax.swing.JPanel pnelPrincipal;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
