/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Dao.ModulodConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Lenovo
 */
public class Painel_Imoveis extends javax.swing.JInternalFrame {

    /**
     * Creates new form Painel_Imoveis
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public Painel_Imoveis() {
        initComponents();
        conexao = ModulodConexao.conector();
        consultarAnuncio();
    }
    
    private void consultarAnuncio() {
        String sql = "SELECT * FROM tbImovel";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            do {
                tblePesquisarAnuncio.setModel(DbUtils.resultSetToTableModel(rs));
            } while (rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnelPrincipal = new javax.swing.JPanel();
        txtPesquisar = new javax.swing.JTextField();
        jSeparatorPesquisar = new javax.swing.JSeparator();
        lblPesquisar = new javax.swing.JLabel();
        cbxCriteriodPesquisar = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblePesquisarAnuncio = new javax.swing.JTable();

        pnelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        txtPesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPesquisar.setText("Pesquisar");
        txtPesquisar.setBorder(null);
        txtPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisarFocusGained(evt);
            }
        });

        jSeparatorPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxCriteriodPesquisarFocusGained(evt);
            }
        });

        lblPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/search_50px_1.png"))); // NOI18N
        lblPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbxCriteriodPesquisarFocusGained(evt);
            }
        });

        cbxCriteriodPesquisar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        cbxCriteriodPesquisar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bairro", "Preço", "Venda", "Aluguer", "Casa", "Flat" }));

        tblePesquisarAnuncio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idImovel", "Bairro", "Tipo de imóvel", "Numero da casa", "Quarteirao", "Dimensao", "Andar", "Descricao", "Preco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblePesquisarAnuncio);

        javax.swing.GroupLayout pnelPrincipalLayout = new javax.swing.GroupLayout(pnelPrincipal);
        pnelPrincipal.setLayout(pnelPrincipalLayout);
        pnelPrincipalLayout.setHorizontalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelPrincipalLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(cbxCriteriodPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPesquisar)
                    .addComponent(jSeparatorPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPesquisar)
                .addGap(93, 93, 93))
            .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnelPrincipalLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jScrollPane1)
                    .addGap(12, 12, 12)))
        );
        pnelPrincipalLayout.setVerticalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelPrincipalLayout.createSequentialGroup()
                        .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCriteriodPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparatorPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPesquisar))
                .addContainerGap(463, Short.MAX_VALUE))
            .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnelPrincipalLayout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(149, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCriteriodPesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxCriteriodPesquisarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCriteriodPesquisarFocusGained

    private void txtPesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisarFocusGained
        // TODO add your handling code here:
        txtPesquisar.setText("");
    }//GEN-LAST:event_txtPesquisarFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxCriteriodPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorPesquisar;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JPanel pnelPrincipal;
    private javax.swing.JTable tblePesquisarAnuncio;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
