/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Dao.ModulodConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Lenovo
 */
public class Painel_Anuncios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Painel_Anuncios
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String nomeUsuario;
    int idUsuario, idImovel;

    public Painel_Anuncios(String nome) {
        initComponents();
        conexao = ModulodConexao.conector();
        nomeUsuario = nome;
    }
    
    public void setNomeUsuario(String nome) {
        nomeUsuario = nome;
    }

    private void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(0, 153, 153));
    }

    private void resetColor(JPanel panel) {
        panel.setBackground(java.awt.Color.red);
    }

    private void registarImoveis() {
        String sql = "insert into tbImovel(bairro,tipo_imovel,nr_casa,quarteirao,dimensao,andar,descricao,preco) values(?,?,?,?,?,?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            String dimensao = txtLargura.getText() + "x" + txtComprimento.getText();
            pst.setString(1, txtBairro.getText());
            pst.setString(2, cbxTipoImovel.getSelectedItem().toString());
            pst.setString(3, txtNrCasa.getText());
            pst.setString(4, txtQuarteirao.getText());
            if (cbxTipoImovel.getSelectedItem().toString().equalsIgnoreCase("Casa")) {
                pst.setString(5, dimensao);
                pst.setInt(6, 0);
            } else if (cbxTipoImovel.getSelectedItem().toString().equalsIgnoreCase("Apartamento")) {
                pst.setString(5, "null");
                pst.setInt(6, Integer.parseInt(txtAndar.getText()));
            }
            pst.setString(7, txtDescrisao.getText());
            pst.setFloat(8, Float.parseFloat(txtPreco.getText()));
            int adicionado = pst.executeUpdate();
            if (adicionado > 0) {
                idUsuario();
                idImovel();
                registarAnuncio();
            } else {
                JOptionPane.showMessageDialog(null, "Prencha correctamente os campos!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void registarAnuncio() {
        String sql = "insert into tbAnuncio(data_publicacao, tipo_anuncio,id_imovel,id_usuario) values(?,?,?,?)";
        try {
            String data = ((JTextField) jDateData.getDateEditor().getUiComponent()).getText();
            //System.out.println(data);
            pst = conexao.prepareStatement(sql);
            pst.setString(1, data);
            pst.setString(2, cbxTipoAnuncio.getSelectedItem().toString());
            pst.setInt(3, idImovel);
            pst.setInt(4, idUsuario);
            int adicionado = pst.executeUpdate();
            if (adicionado > 0) {
                JOptionPane.showMessageDialog(null, "Anúncio publicado!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void idUsuario() {
        String sql = "select idUsuario from tbUsuario where nomeUsuario=" + "'" +nomeUsuario + "'";
        
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            System.out.println(nomeUsuario);
            if (rs.next()) {
                idUsuario = rs.getInt("idUsuario");
                System.out.println(idUsuario);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    
    private void idImovel() {
        String sql = "SELECT idImovel FROM tbImovel ORDER BY idImovel DESC LIMIT 1";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                idImovel = rs.getInt("idImovel");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnelPrincipal = new javax.swing.JPanel();
        pnelMenus = new javax.swing.JPanel();
        btnPesquisar = new javax.swing.JPanel();
        lblIconPesquisar = new javax.swing.JLabel();
        lblPesquisar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        lblIconEliminar = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JPanel();
        lblIconAtualizar = new javax.swing.JLabel();
        lblAtualizar = new javax.swing.JLabel();
        pnelPaineis = new javax.swing.JPanel();
        pnelRegistar = new javax.swing.JPanel();
        lblTipoImovel = new javax.swing.JLabel();
        lblLargura = new javax.swing.JLabel();
        lblComprimento = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblQuarteirao = new javax.swing.JLabel();
        pnelLargura = new javax.swing.JPanel();
        txtLargura = new javax.swing.JTextField();
        pnelComprimento = new javax.swing.JPanel();
        txtComprimento = new javax.swing.JTextField();
        lblAndar = new javax.swing.JLabel();
        pnelAndar = new javax.swing.JPanel();
        txtAndar = new javax.swing.JTextField();
        cbxTipoImovel = new javax.swing.JComboBox();
        txtBairro = new javax.swing.JTextField();
        jSeparatorBairro = new javax.swing.JSeparator();
        txtQuarteirao = new javax.swing.JTextField();
        jSeparatorQuarteirao = new javax.swing.JSeparator();
        lblDescrisao = new javax.swing.JLabel();
        txtDescrisao = new javax.swing.JTextField();
        jSeparatorDescrisao = new javax.swing.JSeparator();
        lblTipoAnuncio = new javax.swing.JLabel();
        cbxTipoAnuncio = new javax.swing.JComboBox();
        btnRegistar = new javax.swing.JButton();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jSeparatorQuarteirao1 = new javax.swing.JSeparator();
        lblDataAnuncio = new javax.swing.JLabel();
        jDateData = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        lblNrCasa = new javax.swing.JLabel();
        txtNrCasa = new javax.swing.JTextField();
        pnelCarregarPaineis = new javax.swing.JPanel();
        jDesktopPaneCarregarPaineis = new javax.swing.JDesktopPane();
        lblVoltar = new javax.swing.JLabel();

        pnelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        pnelMenus.setBackground(new java.awt.Color(255, 255, 255));

        btnPesquisar.setBackground(new java.awt.Color(0, 153, 153));
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
        });

        lblIconPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/view_50px_3.png"))); // NOI18N

        lblPesquisar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lblPesquisar.setText("Pesquisar anúncios");

        javax.swing.GroupLayout btnPesquisarLayout = new javax.swing.GroupLayout(btnPesquisar);
        btnPesquisar.setLayout(btnPesquisarLayout);
        btnPesquisarLayout.setHorizontalGroup(
            btnPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPesquisarLayout.setVerticalGroup(
            btnPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPesquisarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(btnPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPesquisar)
                    .addComponent(lblIconPesquisar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnEliminar.setBackground(new java.awt.Color(0, 153, 153));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        lblIconEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/delete_file_50px_1.png"))); // NOI18N

        lblEliminar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setText("Eliminar anúncios");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconEliminar)
                    .addComponent(lblEliminar))
                .addGap(25, 25, 25))
        );

        btnAtualizar.setBackground(new java.awt.Color(0, 153, 153));
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtualizarMouseClicked(evt);
            }
        });

        lblIconAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/update_file_50px_1.png"))); // NOI18N

        lblAtualizar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        lblAtualizar.setText("Atualizar anúncios");

        javax.swing.GroupLayout btnAtualizarLayout = new javax.swing.GroupLayout(btnAtualizar);
        btnAtualizar.setLayout(btnAtualizarLayout);
        btnAtualizarLayout.setHorizontalGroup(
            btnAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAtualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAtualizar)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        btnAtualizarLayout.setVerticalGroup(
            btnAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAtualizarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(btnAtualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAtualizar)
                    .addComponent(lblIconAtualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnelMenusLayout = new javax.swing.GroupLayout(pnelMenus);
        pnelMenus.setLayout(pnelMenusLayout);
        pnelMenusLayout.setHorizontalGroup(
            pnelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelMenusLayout.createSequentialGroup()
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnelMenusLayout.setVerticalGroup(
            pnelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelMenusLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnelPaineis.setBackground(new java.awt.Color(255, 255, 255));
        pnelPaineis.setLayout(new java.awt.CardLayout());

        pnelRegistar.setBackground(new java.awt.Color(255, 255, 255));

        lblTipoImovel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTipoImovel.setText("* Tipo de imóvel");

        lblLargura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblLargura.setText("* Largura");

        lblComprimento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblComprimento.setText("* Comprimento");

        lblBairro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblBairro.setText("* Bairro");

        lblQuarteirao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblQuarteirao.setText("* Quarteirão");

        pnelLargura.setBackground(java.awt.Color.red);

        javax.swing.GroupLayout pnelLarguraLayout = new javax.swing.GroupLayout(pnelLargura);
        pnelLargura.setLayout(pnelLarguraLayout);
        pnelLarguraLayout.setHorizontalGroup(
            pnelLarguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtLargura, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnelLarguraLayout.setVerticalGroup(
            pnelLarguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtLargura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnelComprimento.setBackground(java.awt.Color.red);

        javax.swing.GroupLayout pnelComprimentoLayout = new javax.swing.GroupLayout(pnelComprimento);
        pnelComprimento.setLayout(pnelComprimentoLayout);
        pnelComprimentoLayout.setHorizontalGroup(
            pnelComprimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnelComprimentoLayout.setVerticalGroup(
            pnelComprimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtComprimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        lblAndar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAndar.setText("* Andar");

        pnelAndar.setBackground(java.awt.Color.red);

        javax.swing.GroupLayout pnelAndarLayout = new javax.swing.GroupLayout(pnelAndar);
        pnelAndar.setLayout(pnelAndarLayout);
        pnelAndarLayout.setHorizontalGroup(
            pnelAndarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAndar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnelAndarLayout.setVerticalGroup(
            pnelAndarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAndar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        cbxTipoImovel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbxTipoImovel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Casa", "Apartamento" }));
        cbxTipoImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoImovelActionPerformed(evt);
            }
        });

        txtBairro.setBorder(null);

        txtQuarteirao.setBorder(null);

        lblDescrisao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDescrisao.setText("* Descrisão");

        txtDescrisao.setBorder(null);

        lblTipoAnuncio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTipoAnuncio.setText("Tipo de anúncio");

        cbxTipoAnuncio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Venda", "Aluguel" }));

        btnRegistar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegistar.setText("Registar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        lblPreco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPreco.setText("* Preço");

        txtPreco.setBorder(null);

        lblDataAnuncio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDataAnuncio.setText("* Data do anúncio");

        jDateData.setBackground(new java.awt.Color(255, 255, 255));
        jDateData.setDateFormatString("yyyy-MM-dd");

        jLabel2.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel2.setText("(ano-MÊS-dia)");

        lblNrCasa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNrCasa.setText("*Nr. casa");

        javax.swing.GroupLayout pnelRegistarLayout = new javax.swing.GroupLayout(pnelRegistar);
        pnelRegistar.setLayout(pnelRegistarLayout);
        pnelRegistarLayout.setHorizontalGroup(
            pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelRegistarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(78, 78, 78))
            .addGroup(pnelRegistarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelRegistarLayout.createSequentialGroup()
                        .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnelRegistarLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(lblBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparatorBairro)
                                    .addComponent(txtBairro))
                                .addGap(92, 92, 92)
                                .addComponent(lblQuarteirao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparatorQuarteirao)
                                    .addComponent(txtQuarteirao, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                            .addGroup(pnelRegistarLayout.createSequentialGroup()
                                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDescrisao)
                                    .addComponent(lblLargura)
                                    .addComponent(lblTipoImovel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnelRegistarLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnRegistar))
                                    .addGroup(pnelRegistarLayout.createSequentialGroup()
                                        .addComponent(cbxTipoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDataAnuncio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateData, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnelRegistarLayout.createSequentialGroup()
                                        .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSeparatorDescrisao, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDescrisao))
                                        .addGap(126, 126, 126)
                                        .addComponent(lblPreco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparatorQuarteirao1)
                                            .addComponent(txtPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                                    .addGroup(pnelRegistarLayout.createSequentialGroup()
                                        .addComponent(pnelLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(lblComprimento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pnelComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(lblAndar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pnelAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                        .addComponent(lblNrCasa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNrCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(34, 34, 34))
                    .addGroup(pnelRegistarLayout.createSequentialGroup()
                        .addComponent(lblTipoAnuncio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxTipoAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnelRegistarLayout.setVerticalGroup(
            pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelRegistarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelRegistarLayout.createSequentialGroup()
                        .addComponent(jDateData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnelRegistarLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(lblComprimento)
                                    .addGap(8, 8, 8))
                                .addComponent(pnelComprimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnelLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(pnelRegistarLayout.createSequentialGroup()
                        .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoImovel)
                            .addComponent(cbxTipoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataAnuncio))
                        .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnelRegistarLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)
                                .addGap(20, 20, 20)
                                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnelRegistarLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblAndar)
                                        .addGap(8, 8, 8))
                                    .addComponent(pnelAndar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnelRegistarLayout.createSequentialGroup()
                                            .addGap(11, 11, 11)
                                            .addComponent(lblNrCasa))
                                        .addComponent(txtNrCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelRegistarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLargura)
                                .addGap(37, 37, 37)))))
                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnelRegistarLayout.createSequentialGroup()
                        .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBairro)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparatorBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnelRegistarLayout.createSequentialGroup()
                        .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuarteirao)
                            .addComponent(txtQuarteirao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparatorQuarteirao, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelRegistarLayout.createSequentialGroup()
                        .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnelRegistarLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblDescrisao))
                            .addGroup(pnelRegistarLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtDescrisao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparatorDescrisao, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoAnuncio)
                            .addComponent(cbxTipoAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(pnelRegistarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnelRegistarLayout.createSequentialGroup()
                                .addComponent(lblPreco)
                                .addGap(8, 8, 8))
                            .addGroup(pnelRegistarLayout.createSequentialGroup()
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparatorQuarteirao1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );

        pnelPaineis.add(pnelRegistar, "card2");

        pnelCarregarPaineis.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPaneCarregarPaineisLayout = new javax.swing.GroupLayout(jDesktopPaneCarregarPaineis);
        jDesktopPaneCarregarPaineis.setLayout(jDesktopPaneCarregarPaineisLayout);
        jDesktopPaneCarregarPaineisLayout.setHorizontalGroup(
            jDesktopPaneCarregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );
        jDesktopPaneCarregarPaineisLayout.setVerticalGroup(
            jDesktopPaneCarregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnelCarregarPaineisLayout = new javax.swing.GroupLayout(pnelCarregarPaineis);
        pnelCarregarPaineis.setLayout(pnelCarregarPaineisLayout);
        pnelCarregarPaineisLayout.setHorizontalGroup(
            pnelCarregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneCarregarPaineis)
        );
        pnelCarregarPaineisLayout.setVerticalGroup(
            pnelCarregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneCarregarPaineis)
        );

        pnelPaineis.add(pnelCarregarPaineis, "card3");

        lblVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Back.png"))); // NOI18N
        lblVoltar.setText("Voltar");
        lblVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnelPrincipalLayout = new javax.swing.GroupLayout(pnelPrincipal);
        pnelPrincipal.setLayout(pnelPrincipalLayout);
        pnelPrincipalLayout.setHorizontalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelMenus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnelPaineis, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnelPrincipalLayout.createSequentialGroup()
                .addComponent(lblVoltar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnelPrincipalLayout.setVerticalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelPrincipalLayout.createSequentialGroup()
                .addComponent(pnelMenus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnelPaineis, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        // TODO add your handling code here:
        registarImoveis();
        
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void cbxTipoImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoImovelActionPerformed
        // TODO add your handling code here:
        if (cbxTipoImovel.getSelectedItem().toString().equals("Casa")) {
            setColor(pnelLargura);
            setColor(pnelComprimento);
            resetColor(pnelAndar);
        } else if (cbxTipoImovel.getSelectedItem().toString().equals("Apartamento")) {
            resetColor(pnelLargura);
            resetColor(pnelComprimento);
            setColor(pnelAndar);
        }
    }//GEN-LAST:event_cbxTipoImovelActionPerformed

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        // TODO add your handling code here:
        pnelRegistar.hide();
        pnelCarregarPaineis.show();
        jDesktopPaneCarregarPaineis.show();
        Pesquisar_Anuncio anuncio = new Pesquisar_Anuncio();
        anuncio.setVisible(true);
        if (jDesktopPaneCarregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCarregarPaineis.add(anuncio);
        } else {
            jDesktopPaneCarregarPaineis.remove(0);
            jDesktopPaneCarregarPaineis.add(anuncio);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void lblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseClicked
        // TODO add your handling code here:
        pnelCarregarPaineis.hide();
        pnelRegistar.show();
    }//GEN-LAST:event_lblVoltarMouseClicked

    private void btnAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizarMouseClicked
        // TODO add your handling code here:
        pnelRegistar.hide();
        pnelCarregarPaineis.show();
        jDesktopPaneCarregarPaineis.show();
        Atualizar_Dados_Anuncio atualizar_anuncio = new Atualizar_Dados_Anuncio("");
        atualizar_anuncio.setVisible(true);
        if (jDesktopPaneCarregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCarregarPaineis.add(atualizar_anuncio);
        } else {
            jDesktopPaneCarregarPaineis.remove(0);
            jDesktopPaneCarregarPaineis.add(atualizar_anuncio);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_btnAtualizarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        pnelRegistar.hide();
        pnelCarregarPaineis.show();
        jDesktopPaneCarregarPaineis.show();
        Eliminar_Anuncio eliminar_anuncio = new Eliminar_Anuncio();
        eliminar_anuncio.setVisible(true);
        if (jDesktopPaneCarregarPaineis.getAllFrames().length == 0) {
            jDesktopPaneCarregarPaineis.add(eliminar_anuncio);
        } else {
            jDesktopPaneCarregarPaineis.remove(0);
            jDesktopPaneCarregarPaineis.add(eliminar_anuncio);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_btnEliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAtualizar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnPesquisar;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JComboBox cbxTipoAnuncio;
    private javax.swing.JComboBox cbxTipoImovel;
    private com.toedter.calendar.JDateChooser jDateData;
    private javax.swing.JDesktopPane jDesktopPaneCarregarPaineis;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparatorBairro;
    private javax.swing.JSeparator jSeparatorDescrisao;
    private javax.swing.JSeparator jSeparatorQuarteirao;
    private javax.swing.JSeparator jSeparatorQuarteirao1;
    private javax.swing.JLabel lblAndar;
    private javax.swing.JLabel lblAtualizar;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblComprimento;
    private javax.swing.JLabel lblDataAnuncio;
    private javax.swing.JLabel lblDescrisao;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblIconAtualizar;
    private javax.swing.JLabel lblIconEliminar;
    private javax.swing.JLabel lblIconPesquisar;
    private javax.swing.JLabel lblLargura;
    private javax.swing.JLabel lblNrCasa;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQuarteirao;
    private javax.swing.JLabel lblTipoAnuncio;
    private javax.swing.JLabel lblTipoImovel;
    private javax.swing.JLabel lblVoltar;
    private javax.swing.JPanel pnelAndar;
    private javax.swing.JPanel pnelCarregarPaineis;
    private javax.swing.JPanel pnelComprimento;
    private javax.swing.JPanel pnelLargura;
    private javax.swing.JPanel pnelMenus;
    private javax.swing.JPanel pnelPaineis;
    private javax.swing.JPanel pnelPrincipal;
    private javax.swing.JPanel pnelRegistar;
    private javax.swing.JTextField txtAndar;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtComprimento;
    private javax.swing.JTextField txtDescrisao;
    private javax.swing.JTextField txtLargura;
    private javax.swing.JTextField txtNrCasa;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuarteirao;
    // End of variables declaration//GEN-END:variables
}
