/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Lenovo
 */
import javax.swing.JPanel;
import java.sql.*;
import Model.Dao.ModulodConexao;
import static View.Sistema_Venda_Arendamento.lblNomeUsuario;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

public class Painel_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Painel_Principal
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Sistema_Venda_Arendamento pnelVenda;
    Painel_Usuario pnelUsuario;
    Painel_Anuncios pnelAnuncio;

    public Painel_Principal() {
        initComponents();
        conexao = ModulodConexao.conector();
        pnelVenda = new Sistema_Venda_Arendamento();
        consultarAnuncio();
    }
    
    public String getUsuario(){
        return pnelVenda.lblNomeUsuario.getText();
    }
    
    private void registarUsuario() {
        String sql = "insert into tbUsuario(nome,nomeUsuario,senha,telefone) values(?,?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtNome.getText());
            pst.setString(2, txtUsuarios.getText());
            pst.setString(3, txtSenha.getText());
            pst.setString(4, txtTelefone.getText());
            int adicionado = pst.executeUpdate();
            if (adicionado > 0) {
                JOptionPane.showMessageDialog(null, "Usuario registado com sucesso!");
                txtNome.setText("");
                txtUsuarios.setText("");
                txtSenha.setText("");
                txtTelefone.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void consultarAnuncio() {
        String sql = "SELECT * FROM tbImovel";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            do {
                tblePesquisarAnuncio.setModel(DbUtils.resultSetToTableModel(rs));
            } while (rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void login() {
        String sql = "select*from tbUsuario where nomeUsuario=? and senha=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtUsuario.getText());
            pst.setString(2, pwdUsuario.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                String user = rs.getString(3);
                String pwd = rs.getString(4);
                if (user.equals(txtUsuario.getText()) && pwd.equals(pwdUsuario.getText())) {
                    pnelVenda.setVisible(true);
                    pnelVenda.lblNomeUsuario.setText(rs.getString(3));
                    pnelVenda.setNomeUsuario(pnelVenda.lblNomeUsuario.getText());
                    //pnelUsuario.Painel_Usuario(pnelVenda.lblNomeUsuario.getText());
                    //pnelAnuncio.setNomeUsuario(pnelVenda.lblNomeUsuario.getText());
                    this.dispose(); 
                    //idUsuario();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha invalido(s)");
                txtUsuario.setText("Nome do usuário");
                pwdUsuario.setText("*************");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnelPrincipal = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        pnelCarregarPaineis = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblePesquisarAnuncio = new javax.swing.JTable();
        btnLogin = new javax.swing.JButton();
        btnCriarConta = new javax.swing.JButton();
        pnelRegistar = new javax.swing.JPanel();
        lblNomeCompleto = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        txtUsuarios = new javax.swing.JTextField();
        btnRegistar = new javax.swing.JButton();
        lblVoltarRegistar = new javax.swing.JLabel();
        jSeparatorNome = new javax.swing.JSeparator();
        jSeparatorUsuario = new javax.swing.JSeparator();
        jSeparatorSenha = new javax.swing.JSeparator();
        txtTelefone = new javax.swing.JTextField();
        jSeparatorTelefone = new javax.swing.JSeparator();
        lblTelefone = new javax.swing.JLabel();
        pnelLogin = new javax.swing.JPanel();
        pnelCredenciais = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        pwdUsuario = new javax.swing.JPasswordField();
        btnAceder = new javax.swing.JButton();
        lblVisualizar = new javax.swing.JLabel();
        lblVoltarLogin = new javax.swing.JLabel();
        lblIconLogin = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pnelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        lblNome.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        lblNome.setText("Gestão de arrendamendos e venda de imóveis");

        pnelCarregarPaineis.setBackground(new java.awt.Color(255, 255, 255));

        tblePesquisarAnuncio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idImovel", "Bairro", "Tipo de imóvel", "Numero da casa", "Quarteirao", "Dimensao", "Andar", "Descricao", "Preco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblePesquisarAnuncio);

        javax.swing.GroupLayout pnelCarregarPaineisLayout = new javax.swing.GroupLayout(pnelCarregarPaineis);
        pnelCarregarPaineis.setLayout(pnelCarregarPaineisLayout);
        pnelCarregarPaineisLayout.setHorizontalGroup(
            pnelCarregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelCarregarPaineisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnelCarregarPaineisLayout.setVerticalGroup(
            pnelCarregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelCarregarPaineisLayout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnCriarConta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCriarConta.setText("Criar conta");
        btnCriarConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnelPrincipalLayout = new javax.swing.GroupLayout(pnelPrincipal);
        pnelPrincipal.setLayout(pnelPrincipalLayout);
        pnelPrincipalLayout.setHorizontalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCriarConta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addComponent(pnelCarregarPaineis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnelPrincipalLayout.setVerticalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnelCarregarPaineis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCriarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnelPrincipal, "card2");

        pnelRegistar.setBackground(new java.awt.Color(255, 255, 255));

        lblNomeCompleto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNomeCompleto.setText("* Nome");

        lblUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUsuario.setText("* Nome de usuário");

        lblSenha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSenha.setText("* Senha");

        txtNome.setBorder(null);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtSenha.setBorder(null);

        txtUsuarios.setBorder(null);

        btnRegistar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegistar.setText("Registar");
        btnRegistar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        lblVoltarRegistar.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lblVoltarRegistar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Back.png"))); // NOI18N
        lblVoltarRegistar.setText("Voltar");
        lblVoltarRegistar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVoltarRegistar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarRegistarMouseClicked(evt);
            }
        });

        txtTelefone.setBorder(null);

        lblTelefone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTelefone.setText("* Telefone");

        javax.swing.GroupLayout pnelRegistarLayout = new javax.swing.GroupLayout(pnelRegistar);
        pnelRegistar.setLayout(pnelRegistarLayout);
        pnelRegistarLayout.setHorizontalGroup(
            pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelRegistarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVoltarRegistar)
                    .addGroup(pnelRegistarLayout.createSequentialGroup()
                        .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUsuario)
                            .addComponent(lblNomeCompleto)
                            .addComponent(lblTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome)
                            .addComponent(jSeparatorNome)
                            .addGroup(pnelRegistarLayout.createSequentialGroup()
                                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnelRegistarLayout.createSequentialGroup()
                                        .addComponent(txtUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(155, 155, 155)
                                        .addComponent(lblSenha))
                                    .addComponent(jSeparatorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                    .addComponent(jSeparatorSenha)))
                            .addComponent(btnRegistar)
                            .addComponent(jSeparatorTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(txtTelefone))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        pnelRegistarLayout.setVerticalGroup(
            pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelRegistarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVoltarRegistar)
                .addGap(94, 94, 94)
                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCompleto)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparatorSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(pnelRegistarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        getContentPane().add(pnelRegistar, "card3");

        pnelLogin.setBackground(new java.awt.Color(0, 153, 153));

        pnelCredenciais.setBackground(new java.awt.Color(255, 255, 255));
        pnelCredenciais.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUsuario.setText("Nome do usuário");
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
        });

        pwdUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pwdUsuario.setText("jPasswordField1");
        pwdUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdUsuarioFocusGained(evt);
            }
        });

        btnAceder.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAceder.setText("Login");
        btnAceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcederActionPerformed(evt);
            }
        });

        lblVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Eye.png"))); // NOI18N
        lblVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVisualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnelCredenciaisLayout = new javax.swing.GroupLayout(pnelCredenciais);
        pnelCredenciais.setLayout(pnelCredenciaisLayout);
        pnelCredenciaisLayout.setHorizontalGroup(
            pnelCredenciaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelCredenciaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelCredenciaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario)
                    .addComponent(pwdUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelCredenciaisLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceder))
                    .addGroup(pnelCredenciaisLayout.createSequentialGroup()
                        .addComponent(lblVisualizar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnelCredenciaisLayout.setVerticalGroup(
            pnelCredenciaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelCredenciaisLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(pwdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVisualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblVoltarLogin.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lblVoltarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Back.png"))); // NOI18N
        lblVoltarLogin.setText("Voltar");
        lblVoltarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVoltarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarLoginMouseClicked(evt);
            }
        });

        lblIconLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/user_groups_127px.png"))); // NOI18N

        lblLogin.setFont(new java.awt.Font("Sylfaen", 0, 36)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Login");

        javax.swing.GroupLayout pnelLoginLayout = new javax.swing.GroupLayout(pnelLogin);
        pnelLogin.setLayout(pnelLoginLayout);
        pnelLoginLayout.setHorizontalGroup(
            pnelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelLoginLayout.createSequentialGroup()
                .addGroup(pnelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblVoltarLogin)
                        .addGap(337, 337, 337)
                        .addComponent(lblIconLogin))
                    .addGroup(pnelLoginLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(pnelCredenciais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnelLoginLayout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(lblLogin)))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        pnelLoginLayout.setVerticalGroup(
            pnelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVoltarLogin)
                    .addComponent(lblIconLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnelCredenciais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnelLogin, "card4");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarContaActionPerformed
        // TODO add your handling code here:
        pnelPrincipal.hide();
        pnelRegistar.show();
    }//GEN-LAST:event_btnCriarContaActionPerformed

    private void lblVoltarRegistarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarRegistarMouseClicked
        // TODO add your handling code here:
        pnelRegistar.hide();
        pnelPrincipal.show();
    }//GEN-LAST:event_lblVoltarRegistarMouseClicked

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        pnelPrincipal.hide();
        pnelLogin.show();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblVoltarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarLoginMouseClicked
        // TODO add your handling code here:
        pnelLogin.hide();
        pnelPrincipal.show();
    }//GEN-LAST:event_lblVoltarLoginMouseClicked

    private void pwdUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdUsuarioFocusGained
        // TODO add your handling code here:
        pwdUsuario.setText("");
        pwdUsuario.setEchoChar(('*'));
    }//GEN-LAST:event_pwdUsuarioFocusGained

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        // TODO add your handling code here:
        txtUsuario.setText("");
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        // TODO add your handling code here:
        registarUsuario();
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void btnAcederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcederActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btnAcederActionPerformed

    private void lblVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisualizarMouseClicked
        // TODO add your handling code here:
        pwdUsuario.setEchoChar((char) 0);
    }//GEN-LAST:event_lblVisualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceder;
    private javax.swing.JButton btnCriarConta;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorNome;
    private javax.swing.JSeparator jSeparatorSenha;
    private javax.swing.JSeparator jSeparatorTelefone;
    private javax.swing.JSeparator jSeparatorUsuario;
    private javax.swing.JLabel lblIconLogin;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVisualizar;
    private javax.swing.JLabel lblVoltarLogin;
    private javax.swing.JLabel lblVoltarRegistar;
    private javax.swing.JPanel pnelCarregarPaineis;
    private javax.swing.JPanel pnelCredenciais;
    private javax.swing.JPanel pnelLogin;
    private javax.swing.JPanel pnelPrincipal;
    private javax.swing.JPanel pnelRegistar;
    private javax.swing.JPasswordField pwdUsuario;
    private javax.swing.JTable tblePesquisarAnuncio;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuarios;
    // End of variables declaration//GEN-END:variables
}
