/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class Sistema_Venda_Arendamento extends javax.swing.JFrame {

    /**
     * Creates new form Sistema_Venda_Arendamento
     */
    Painel_Imoveis imoveis;
    Painel_Principal p; 
    String nomeUsuario;
    Painel_Usuario pnelUsuario;
    Painel_Anuncios pnelAnuncios;

    public Sistema_Venda_Arendamento() {
        initComponents();
        imoveis = new Painel_Imoveis();
        imoveis.setVisible(true);
        desktopPaneCarregarPaineis.add(imoveis);
        pnelUsuario = new Painel_Usuario("");
        pnelAnuncios = new Painel_Anuncios("");
    }
    
    public void setNomeUsuario(String nome) {
        nomeUsuario = nome;
    }
    
    private void setColor(JPanel[] pnelOpac) {
        for (int i = 0; i < pnelOpac.length; i++) {
            pnelOpac[i].setOpaque(false);
        }
    }
    
    public JLabel getlblNomeUsuario(){
        return lblNomeUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnelPrincipal = new javax.swing.JPanel();
        pnelMenus = new javax.swing.JPanel();
        btnImovel = new javax.swing.JPanel();
        pnelOpacImovel = new javax.swing.JPanel();
        lblIconImovel = new javax.swing.JLabel();
        lblImoveis = new javax.swing.JLabel();
        btnAnuncio = new javax.swing.JPanel();
        pnelOpacAnuncio = new javax.swing.JPanel();
        lblIconAnuncio = new javax.swing.JLabel();
        lblAnuncios = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JPanel();
        pnelOpacUsuarios = new javax.swing.JPanel();
        lblIconUsuario = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();
        lblIniciais = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JPanel();
        pnelOpacLogOut = new javax.swing.JPanel();
        lblIconLogOut = new javax.swing.JLabel();
        lblLogOut = new javax.swing.JLabel();
        lblNomeUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        desktopPaneCarregarPaineis = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        pnelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        pnelMenus.setBackground(new java.awt.Color(0, 153, 153));

        btnImovel.setBackground(new java.awt.Color(255, 255, 255));
        btnImovel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImovel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImovelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnImovelMousePressed(evt);
            }
        });

        pnelOpacImovel.setBackground(new java.awt.Color(31, 60, 82));

        javax.swing.GroupLayout pnelOpacImovelLayout = new javax.swing.GroupLayout(pnelOpacImovel);
        pnelOpacImovel.setLayout(pnelOpacImovelLayout);
        pnelOpacImovelLayout.setHorizontalGroup(
            pnelOpacImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pnelOpacImovelLayout.setVerticalGroup(
            pnelOpacImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblIconImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/house_with_a_garden_50px.png"))); // NOI18N

        lblImoveis.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        lblImoveis.setForeground(new java.awt.Color(0, 153, 153));
        lblImoveis.setText("Imóveis");

        javax.swing.GroupLayout btnImovelLayout = new javax.swing.GroupLayout(btnImovel);
        btnImovel.setLayout(btnImovelLayout);
        btnImovelLayout.setHorizontalGroup(
            btnImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnImovelLayout.createSequentialGroup()
                .addComponent(pnelOpacImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIconImovel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImoveis)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnImovelLayout.setVerticalGroup(
            btnImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelOpacImovel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnImovelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImoveis)
                    .addComponent(lblIconImovel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAnuncio.setBackground(new java.awt.Color(255, 255, 255));
        btnAnuncio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnuncio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnuncioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAnuncioMousePressed(evt);
            }
        });

        pnelOpacAnuncio.setBackground(new java.awt.Color(31, 60, 82));
        pnelOpacAnuncio.setOpaque(false);

        javax.swing.GroupLayout pnelOpacAnuncioLayout = new javax.swing.GroupLayout(pnelOpacAnuncio);
        pnelOpacAnuncio.setLayout(pnelOpacAnuncioLayout);
        pnelOpacAnuncioLayout.setHorizontalGroup(
            pnelOpacAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pnelOpacAnuncioLayout.setVerticalGroup(
            pnelOpacAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblIconAnuncio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/communication_50px.png"))); // NOI18N

        lblAnuncios.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        lblAnuncios.setForeground(new java.awt.Color(0, 153, 153));
        lblAnuncios.setText("Anúncios");

        javax.swing.GroupLayout btnAnuncioLayout = new javax.swing.GroupLayout(btnAnuncio);
        btnAnuncio.setLayout(btnAnuncioLayout);
        btnAnuncioLayout.setHorizontalGroup(
            btnAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAnuncioLayout.createSequentialGroup()
                .addComponent(pnelOpacAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIconAnuncio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAnuncios)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnAnuncioLayout.setVerticalGroup(
            btnAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelOpacAnuncio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnAnuncioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnAnuncioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAnuncios)
                    .addComponent(lblIconAnuncio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUsuarioMousePressed(evt);
            }
        });

        pnelOpacUsuarios.setBackground(new java.awt.Color(31, 60, 82));
        pnelOpacUsuarios.setOpaque(false);

        javax.swing.GroupLayout pnelOpacUsuariosLayout = new javax.swing.GroupLayout(pnelOpacUsuarios);
        pnelOpacUsuarios.setLayout(pnelOpacUsuariosLayout);
        pnelOpacUsuariosLayout.setHorizontalGroup(
            pnelOpacUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pnelOpacUsuariosLayout.setVerticalGroup(
            pnelOpacUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblIconUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/ser_groups_50px_1.png"))); // NOI18N

        lblUsuarios.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(0, 153, 153));
        lblUsuarios.setText("Usuários");

        javax.swing.GroupLayout btnUsuarioLayout = new javax.swing.GroupLayout(btnUsuario);
        btnUsuario.setLayout(btnUsuarioLayout);
        btnUsuarioLayout.setHorizontalGroup(
            btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUsuarioLayout.createSequentialGroup()
                .addComponent(pnelOpacUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIconUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarios)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnUsuarioLayout.setVerticalGroup(
            btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelOpacUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsuarios)
                    .addComponent(lblIconUsuario))
                .addGap(10, 10, 10))
        );

        lblIniciais.setFont(new java.awt.Font("Arial", 0, 68)); // NOI18N
        lblIniciais.setForeground(new java.awt.Color(255, 255, 255));
        lblIniciais.setText("GAVI");

        lblNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Gestão de arrendamendos e venda de imóveis");

        btnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogOutMousePressed(evt);
            }
        });

        pnelOpacLogOut.setBackground(new java.awt.Color(31, 60, 82));
        pnelOpacLogOut.setOpaque(false);

        javax.swing.GroupLayout pnelOpacLogOutLayout = new javax.swing.GroupLayout(pnelOpacLogOut);
        pnelOpacLogOut.setLayout(pnelOpacLogOutLayout);
        pnelOpacLogOutLayout.setHorizontalGroup(
            pnelOpacLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        pnelOpacLogOutLayout.setVerticalGroup(
            pnelOpacLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblIconLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/logout_rounded_left_50px.png"))); // NOI18N

        lblLogOut.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        lblLogOut.setForeground(new java.awt.Color(0, 153, 153));
        lblLogOut.setText("Logout");

        javax.swing.GroupLayout btnLogOutLayout = new javax.swing.GroupLayout(btnLogOut);
        btnLogOut.setLayout(btnLogOutLayout);
        btnLogOutLayout.setHorizontalGroup(
            btnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogOutLayout.createSequentialGroup()
                .addComponent(pnelOpacLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIconLogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnLogOutLayout.setVerticalGroup(
            btnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelOpacLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnLogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogOut)
                    .addComponent(lblIconLogOut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNomeUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeUsuario.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bem-vindo!");

        javax.swing.GroupLayout pnelMenusLayout = new javax.swing.GroupLayout(pnelMenus);
        pnelMenus.setLayout(pnelMenusLayout);
        pnelMenusLayout.setHorizontalGroup(
            pnelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnImovel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAnuncio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnelMenusLayout.createSequentialGroup()
                .addGroup(pnelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnelMenusLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNome))
                    .addGroup(pnelMenusLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblIniciais)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnelMenusLayout.createSequentialGroup()
                .addGroup(pnelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnelMenusLayout.setVerticalGroup(
            pnelMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelMenusLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblIniciais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNome)
                .addGap(37, 37, 37)
                .addComponent(btnImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout desktopPaneCarregarPaineisLayout = new javax.swing.GroupLayout(desktopPaneCarregarPaineis);
        desktopPaneCarregarPaineis.setLayout(desktopPaneCarregarPaineisLayout);
        desktopPaneCarregarPaineisLayout.setHorizontalGroup(
            desktopPaneCarregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        desktopPaneCarregarPaineisLayout.setVerticalGroup(
            desktopPaneCarregarPaineisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnelPrincipalLayout = new javax.swing.GroupLayout(pnelPrincipal);
        pnelPrincipal.setLayout(pnelPrincipalLayout);
        pnelPrincipalLayout.setHorizontalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelPrincipalLayout.createSequentialGroup()
                .addComponent(pnelMenus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPaneCarregarPaineis))
        );
        pnelPrincipalLayout.setVerticalGroup(
            pnelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelMenus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(desktopPaneCarregarPaineis)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnuncioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnuncioMousePressed
        // TODO add your handling code here:
        pnelOpacAnuncio.setOpaque(true);
        setColor(new JPanel[]{pnelOpacUsuarios, pnelOpacImovel});
    }//GEN-LAST:event_btnAnuncioMousePressed

    private void btnUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMousePressed
        // TODO add your handling code here:
        pnelOpacUsuarios.setOpaque(true);
        setColor(new JPanel[]{pnelOpacAnuncio, pnelOpacImovel});
    }//GEN-LAST:event_btnUsuarioMousePressed

    private void btnAnuncioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnuncioMouseClicked
        // TODO add your handling code here:
        desktopPaneCarregarPaineis.show();
        Painel_Anuncios anuncio = new Painel_Anuncios(nomeUsuario);
        anuncio.setVisible(true);
        if (desktopPaneCarregarPaineis.getAllFrames().length == 0) {
            desktopPaneCarregarPaineis.add(anuncio);
        } else {
            desktopPaneCarregarPaineis.remove(0);
            desktopPaneCarregarPaineis.add(anuncio);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_btnAnuncioMouseClicked

    private void btnUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMouseClicked
        // TODO add your handling code here:
        desktopPaneCarregarPaineis.show();
        Painel_Usuario usuario = new Painel_Usuario(nomeUsuario);
        usuario.setVisible(true);
        if (desktopPaneCarregarPaineis.getAllFrames().length == 0) {
            desktopPaneCarregarPaineis.add(usuario);
        } else {
            desktopPaneCarregarPaineis.remove(0);
            desktopPaneCarregarPaineis.add(usuario);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_btnUsuarioMouseClicked

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        // TODO add your handling code here:
        Painel_Principal principal = new Painel_Principal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void btnImovelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImovelMouseClicked
        // TODO add your handling code here:
        desktopPaneCarregarPaineis.show();
        Painel_Imoveis imoveis = new Painel_Imoveis();
        imoveis.setVisible(true);
        if (desktopPaneCarregarPaineis.getAllFrames().length == 0) {
            desktopPaneCarregarPaineis.add(imoveis);
        } else {
            desktopPaneCarregarPaineis.remove(0);
            desktopPaneCarregarPaineis.add(imoveis);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_btnImovelMouseClicked

    private void btnImovelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImovelMousePressed
        // TODO add your handling code here:
        pnelOpacImovel.setOpaque(true);
        setColor(new JPanel[]{pnelOpacUsuarios, pnelOpacAnuncio});
    }//GEN-LAST:event_btnImovelMousePressed

    private void btnLogOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMousePressed
        // TODO add your handling code here:
        pnelOpacLogOut.setOpaque(true);
        setColor(new JPanel[]{pnelOpacUsuarios, pnelOpacAnuncio,pnelOpacImovel});
    }//GEN-LAST:event_btnLogOutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema_Venda_Arendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema_Venda_Arendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema_Venda_Arendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema_Venda_Arendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema_Venda_Arendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAnuncio;
    private javax.swing.JPanel btnImovel;
    private javax.swing.JPanel btnLogOut;
    private javax.swing.JPanel btnUsuario;
    private javax.swing.JDesktopPane desktopPaneCarregarPaineis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAnuncios;
    private javax.swing.JLabel lblIconAnuncio;
    private javax.swing.JLabel lblIconImovel;
    private javax.swing.JLabel lblIconLogOut;
    private javax.swing.JLabel lblIconUsuario;
    private javax.swing.JLabel lblImoveis;
    private javax.swing.JLabel lblIniciais;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblNome;
    public static javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JPanel pnelMenus;
    private javax.swing.JPanel pnelOpacAnuncio;
    private javax.swing.JPanel pnelOpacImovel;
    private javax.swing.JPanel pnelOpacLogOut;
    private javax.swing.JPanel pnelOpacUsuarios;
    private javax.swing.JPanel pnelPrincipal;
    // End of variables declaration//GEN-END:variables
}
